version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mabinogi_items_db
    environment:
      POSTGRES_DB: mabinogi_items
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: